spring:
  datasource:
    url: jdbc:mysql://cpsoa.mooo.com:13306/proyecto_pacha_cano_iw3?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true&serverTimezone=America/Argentina/Cordoba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certSOA.p12
    key-store-password: pc2022
    key-alias: pcSOA
  port: 8443

mail:
  MAIL_FROM: graylogpc2020@gmail.com
  HOST: smtp.gmail.com
  PORT: 587
  USERNAME: graylogpc2020@gmail.com
  PASSWORD: bvdmvxdoqivcfzyf

endpoints:
  urls:
    urlBase: http://localhost:8080


