spring:
  datasource:
    url: jdbc:mysql://db-iw3.cs9qzgc6jxbe.us-east-1.rds.amazonaws.com:3305/proyecto_pacha_cano_iw3?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true&serverTimezone=America/Argentina/Cordoba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: IceCream2020

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

mail:
  MAIL_FROM: graylogpc2020@gmail.com
  HOST: smtp.gmail.com
  PORT: 587
  USERNAME: graylogpc2020@gmail.com
  PASSWORD: bvdmvxdoqivcfzyf

endpoints:
  urls:
    urlBase: http://localhost:8080


