spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyecto_pacha_cano_iw3?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always



